apiVersion: v1
kind: ServiceAccount
metadata:
  name: spring-app-sa
  namespace: proxy
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: spring-app
  namespace: proxy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: spring-app
  template:
    metadata:
      labels:
        app: spring-app
    spec: 
      serviceAccountName: spring-app-sa
      containers:
        - name: spring-app
          image: ttl.sh/spring-app
          ports:
            - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: spring-app
  namespace: proxy
spec:
  selector:
    app: spring-app
  ports:
    - port: 80
      targetPort: 8080
